import uuid
import datetime
from sqlalchemy import Column, String, Float, DateTime, ForeignKey, UUID, Text, JSON
from sqlalchemy.orm import relationship
from app.database import Base

class AIRecommendation(Base):
    """
    Stores persisted executive recommendations generated by EVE AI COO.
    """
    __tablename__ = "ai_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    organization_id = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False)
    agent_source = Column(String, nullable=False)  # "coo" | "finance" | "operations"
    recommendation = Column(Text, nullable=False)
    reasoning_summary = Column(Text, nullable=False)
    
    # JSON arrays or structures
    data_used = Column(JSON, nullable=False)
    risk_factors = Column(JSON, nullable=False)
    opportunity_factors = Column(JSON, nullable=False)
    
    confidence_level = Column(Float, nullable=False)
    expected_outcome = Column(Text, nullable=True)
    actual_outcome = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    # Relationships
    organization = relationship("Organization", back_populates="ai_recommendations")
