from sqlalchemy import DateTime
import uuid
# ==============================================================================
# PURPOSE: Database model for structured agentic Artifacts (e.g., Reports, Summaries).
# DATA FLOW: Generated by the executive coordinator, saved here, and fetched by frontend dashboard views.
# EXTENSION POINTS: Add approval states, revision control logs, or export links.
# ARCHITECTURAL DECISION:
# - Artifacts store raw JSON payloads in `structured_content` to decouple the DB schema
#   from specific report layouts (which will evolve rapidly).
# ==============================================================================

import datetime
from sqlalchemy import Column, Integer, String, ForeignKey, JSON, UUID
from sqlalchemy.orm import relationship
from app.database import Base


class Artifact(Base):
    """
    Represents a structured, read-only decision report produced by EVE workflows.
    """
    __tablename__ = "artifacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    organization_id = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    artifact_type = Column(String, index=True, nullable=False) # e.g. inventory_report, pricing_report, executive_report
    title = Column(String, nullable=False)
    structured_content = Column(JSON, nullable=False) # JSON structure corresponding to report type
    version = Column(Integer, default=1, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    organization = relationship("Organization", back_populates="artifacts")
