from sqlalchemy import DateTime
import uuid
# ==============================================================================
# PURPOSE: Database models for short-term chat histories and long-term vector memories.
# DATA FLOW: Read/write by memory manager. Embeddings generated by Gemini are saved in MemoryEntry.
# EXTENSION POINTS: Add semantic grouping tags, parent conversation references, and search rankings.
# ARCHITECTURAL DECISION:
# - Leverages pgvector on PostgreSQL for native vector similarity searches.
# - Implements a custom TypeDecorator (SafeVector) to fallback cleanly to String-based
#   JSON lists on SQLite, ensuring high developer portability.
# - Gemini embedding models (e.g. text-embedding-004) return 768 dimensions.
# ==============================================================================

import datetime
import json
from sqlalchemy import Column, String, ForeignKey, Text, JSON, UUID
from sqlalchemy.types import TypeDecorator
from sqlalchemy.orm import relationship
from app.database import Base


class SafeVector(TypeDecorator):
    """
    TypeDecorator that resolves to pgvector's Vector type when running on PostgreSQL,
    and falls back to String (JSON serialized array) on SQLite.
    """
    impl = Text

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            try:
                from pgvector.sqlalchemy import Vector
                return dialect.type_descriptor(Vector(768)) # Gemini default embedding dimension
            except ImportError:
                pass
        return dialect.type_descriptor(Text)

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        if dialect.name == "postgresql":
            return value
        # For SQLite fallback, serialize float array to string
        if isinstance(value, list):
            return json.dumps([float(x) for x in value])
        return value

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        if dialect.name == "postgresql":
            return value
        # For SQLite fallback, parse back to list of floats
        try:
            return json.loads(value)
        except Exception:
            return value


class ConversationSession(Base):
    """
    Represents a specific multi-agent chat session context.
    """
    __tablename__ = "conversation_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    organization_id = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    organization = relationship("Organization", back_populates="sessions")
    messages = relationship("ChatMessage", back_populates="session", cascade="all, delete-orphan")


class ChatMessage(Base):
    """
    Represents a message exchange inside a chat session.
    """
    __tablename__ = "chat_messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    session_id = Column(UUID(as_uuid=True), ForeignKey("conversation_sessions.id", ondelete="CASCADE"), nullable=False)
    role = Column(String, nullable=False)  # user, assistant, system
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    session = relationship("ConversationSession", back_populates="messages")


class MemoryEntry(Base):
    """
    Stores long-term vector semantic summaries of key events, preferences, or calculations.
    """
    __tablename__ = "memory_entries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    organization_id = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    content = Column(Text, nullable=False)
    embedding = Column(SafeVector, nullable=True) # Vector storage column
    metadata_json = Column(JSON, nullable=True)   # Extra query filters
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    organization = relationship("Organization", back_populates="memories")
