"use client";

import { useEffect, useState } from "react";
import { X, Loader2, Sparkles, Award, ArrowUpRight, TrendingUp, AlertTriangle, Target } from "lucide-react";
import { getRecommendations } from "@/services/executiveService";
import { AIRecommendationResponse } from "@/types/executive";

interface RecommendationHistoryPanelProps {
  isOpen: boolean;
  onClose: () => void;
  token: string;
}

export function RecommendationHistoryPanel({ isOpen, onClose, token }: RecommendationHistoryPanelProps) {
  const [recommendations, setRecommendations] = useState<AIRecommendationResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const fetchRecommendations = async () => {
    if (!token) return;
    setLoading(true);
    try {
      const data = await getRecommendations(token, 20);
      setRecommendations(data);
    } catch (err) {
      console.error("Failed to load recommendations:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchRecommendations();
    }
  }, [isOpen, token]);

  if (!isOpen) return null;

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  const getSourceBadge = (source: string) => {
    const s = source.toLowerCase();
    if (s === "finance") {
      return (
        <span className="px-2 py-0.5 text-[10px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-md">
          Finance Agent
        </span>
      );
    } else if (s === "operations" || s === "inventory") {
      return (
        <span className="px-2 py-0.5 text-[10px] font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/20 rounded-md">
          Operations Agent
        </span>
      );
    } else if (s === "client" || s === "clients") {
      return (
        <span className="px-2 py-0.5 text-[10px] font-semibold bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 rounded-md">
          Client Agent
        </span>
      );
    } else if (s === "growth") {
      return (
        <span className="px-2 py-0.5 text-[10px] font-semibold bg-pink-500/10 text-pink-400 border border-pink-500/20 rounded-md">
          Growth Agent
        </span>
      );
    } else {
      return (
        <span className="px-2 py-0.5 text-[10px] font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 rounded-md">
          COO Synthesis
        </span>
      );
    }
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      {/* Overlay */}
      <div 
        className="absolute inset-0 bg-background backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />

      <div className="absolute inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-md bg-card border-l border-border flex flex-col shadow-2xl">
          {/* Header */}
          <div className="px-6 py-5 border-b border-border bg-card backdrop-blur-md flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 bg-indigo-500/10 text-indigo-400 rounded-lg border border-indigo-500/20">
                <Sparkles size={18} />
              </div>
              <div>
                <h2 className="text-base font-semibold text-foreground">Recommendation History</h2>
                <p className="text-xs text-muted-foreground">Past strategic insights generated by EVE agents</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="text-muted-foreground hover:text-foreground transition-colors p-1 hover:bg-secondary rounded-md"
            >
              <X size={18} />
            </button>
          </div>

          {/* List Area */}
          <div className="flex-1 overflow-y-auto p-6 space-y-4">
            {loading ? (
              <div className="flex flex-col items-center justify-center h-48 gap-3 text-muted-foreground">
                <Loader2 size={24} className="animate-spin text-indigo-500" />
                <span className="text-xs">Loading EVE recommendations...</span>
              </div>
            ) : recommendations.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground border border-dashed border-border rounded-xl p-6">
                <p className="text-sm">No recommendations logged yet.</p>
                <p className="text-xs text-muted-foreground mt-1">Recommendations are automatically generated during AI chats and daily brief runs.</p>
              </div>
            ) : (
              recommendations.map((item) => {
                const isExpanded = expandedId === item.id;
                const formattedDate = new Date(item.created_at).toLocaleString();
                const confidence = Math.round(item.confidence_level * 100);

                return (
                  <div 
                    key={item.id} 
                    className="bg-background border border-border rounded-xl p-4 hover:border-border transition-all flex flex-col gap-3"
                  >
                    {/* Source and Time */}
                    <div className="flex items-center justify-between">
                      {getSourceBadge(item.agent_source)}
                      <span className="text-[10px] text-muted-foreground font-medium">
                        {formattedDate}
                      </span>
                    </div>

                    {/* Content */}
                    <div>
                      <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
                        Recommendation
                      </h4>
                      <p className="text-sm font-medium text-foreground leading-relaxed">
                        {item.recommendation}
                      </p>
                      {item.influenced_by_goals && item.influenced_by_goals.length > 0 && (
                        <div className="mt-2.5 flex flex-wrap gap-1.5 items-center">
                          <span className="text-[10px] text-slate-450 font-bold uppercase tracking-wider flex items-center gap-0.5">
                            <Target size={11} className="text-indigo-400" /> Influenced by:
                          </span>
                          {item.influenced_by_goals.map((g) => (
                            <span
                              key={g.id}
                              title={g.description}
                              className={`text-[9px] font-bold px-2 py-0.5 rounded-full border cursor-help ${
                                g.goal_type === 'profitability' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                                g.goal_type === 'growth' ? 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20' :
                                g.goal_type === 'cost_reduction' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                                'bg-slate-500/10 text-muted-foreground border-slate-500/20'
                              }`}
                            >
                              {g.goal_type.replace('_', ' ')}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Reasoning Summary (only if expanded or snippet) */}
                    <div>
                      <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
                        Reasoning Summary
                      </h4>
                      <p className="text-xs text-muted-foreground leading-relaxed">
                        {isExpanded ? item.reasoning_summary : `${item.reasoning_summary.slice(0, 80)}...`}
                      </p>
                    </div>

                    {/* Confidence gauge */}
                    <div className="flex items-center justify-between text-xs pt-1 border-t border-border">
                      <div className="flex items-center gap-1.5 text-muted-foreground">
                        <Award size={13} className="text-indigo-400" />
                        <span>Confidence:</span>
                        <span className="font-semibold text-foreground">{confidence}%</span>
                      </div>
                      <button
                        onClick={() => toggleExpand(item.id)}
                        className="text-indigo-400 hover:text-indigo-300 font-semibold text-xs flex items-center gap-0.5 outline-none"
                      >
                        {isExpanded ? "Show Less" : "Details"}
                        <ArrowUpRight size={12} className={`transition-transform ${isExpanded ? "rotate-45" : ""}`} />
                      </button>
                    </div>

                    {/* Expanded details */}
                    {isExpanded && (
                      <div className="space-y-3 pt-3 border-t border-border animate-in fade-in slide-in-from-top-1 duration-150">
                        {/* Data Used */}
                        {item.data_used && item.data_used.length > 0 && (
                          <div>
                            <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1">
                              <TrendingUp size={10} className="text-cyan-400" /> Data Indicators
                            </span>
                            <ul className="list-disc list-inside text-xs text-muted-foreground mt-1 pl-1 space-y-0.5">
                              {item.data_used.map((data: any, idx: number) => (
                                <li key={idx} className="truncate">{String(data)}</li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* Risks & Opportunities */}
                        <div className="grid grid-cols-2 gap-3">
                          {item.risk_factors && item.risk_factors.length > 0 && (
                            <div>
                              <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1">
                                <AlertTriangle size={10} className="text-amber-400" /> Risk Factors
                              </span>
                              <ul className="text-[11px] text-muted-foreground mt-1 list-disc list-inside space-y-0.5 pl-1">
                                {item.risk_factors.map((risk, idx) => (
                                  <li key={idx} className="leading-tight">{risk}</li>
                                ))}
                              </ul>
                            </div>
                          )}

                          {item.opportunity_factors && item.opportunity_factors.length > 0 && (
                            <div>
                              <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-1">
                                <Sparkles size={10} className="text-emerald-400" /> Opportunities
                              </span>
                              <ul className="text-[11px] text-muted-foreground mt-1 list-disc list-inside space-y-0.5 pl-1">
                                {item.opportunity_factors.map((opp, idx) => (
                                  <li key={idx} className="leading-tight">{opp}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
