"""add_evidence_validation_and_trust_score

Revision ID: 012c75bbd96c
Revises: e8ef8228c6c5
Create Date: 2026-07-17 04:11:32.032260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012c75bbd96c'
down_revision: Union[str, Sequence[str], None] = 'e8ef8228c6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_traces', sa.Column('evidence_validation_status', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('evidence_validation_reason', sa.Text(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('confidence_governance_flag', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('trust_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_traces', 'trust_score')
    op.drop_column('recommendation_traces', 'confidence_governance_flag')
    op.drop_column('recommendation_traces', 'evidence_validation_reason')
    op.drop_column('recommendation_traces', 'evidence_validation_status')
    # ### end Alembic commands ###
