"""Sync schema

Revision ID: 96413e027c87
Revises: 62516a41b9b4
Create Date: 2026-07-15 11:30:40.662135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96413e027c87'
down_revision: Union[str, Sequence[str], None] = '62516a41b9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'before_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'after_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.execute("UPDATE audit_logs SET user_id = NULL WHERE user_id NOT IN (SELECT id FROM profiles)")
    op.create_foreign_key(None, 'audit_logs', 'profiles', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('intelligence_snapshots', 'inventory_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('intelligence_snapshots', 'at_risk_skus',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'dead_stock_skus',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'revenue_at_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('intelligence_snapshots', 'working_capital_locked',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('intelligence_snapshots', 'business_health_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('intelligence_snapshots', 'top_risk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'top_opportunity_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'top_action_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_processed_documents_sha256_hash'), 'processed_documents', ['sha256_hash'], unique=False)
    op.add_column('products', sa.Column('parent_product_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_parent_product_id'), 'products', ['parent_product_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_email'), 'waitlist_entries', ['email'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_user_id'), 'waitlist_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_entries_user_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_email'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_products_parent_product_id'), table_name='products')
    op.drop_column('products', 'parent_product_id')
    op.drop_index(op.f('ix_processed_documents_sha256_hash'), table_name='processed_documents')
    op.alter_column('intelligence_snapshots', 'top_action_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'top_opportunity_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'top_risk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'business_health_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('intelligence_snapshots', 'working_capital_locked',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('intelligence_snapshots', 'revenue_at_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('intelligence_snapshots', 'dead_stock_skus',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'at_risk_skus',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('intelligence_snapshots', 'inventory_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'after_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'before_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
