"""add_analysis_status

Revision ID: a4b2091b9563
Revises: 012c75bbd96c
Create Date: 2026-07-18 07:14:14.263897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b2091b9563'
down_revision: Union[str, Sequence[str], None] = '012c75bbd96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('analysis_status', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'analysis_status')
    # ### end Alembic commands ###
