"""add_true_decision_traceability_fields

Revision ID: e8ef8228c6c5
Revises: a7b8c9d0e1f2
Create Date: 2026-07-17 03:46:37.722943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ef8228c6c5'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['recommendation_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_audit_events_id'), 'recommendation_audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_audit_events_trace_id'), 'recommendation_audit_events', ['trace_id'], unique=False)
    op.add_column('recommendation_traces', sa.Column('triggered_by_user_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('triggered_by_email', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('trigger_type', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('source_agent', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('created_from_query', sa.Boolean(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('llm_provider', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('llm_model_version', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('top_p', sa.Float(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('top_k', sa.Integer(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('system_prompt_hash', sa.String(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('raw_prompt', sa.Text(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('raw_response', sa.Text(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('response_timestamp', sa.DateTime(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('input_metrics', sa.JSON(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('business_rules', sa.JSON(), nullable=True))
    op.add_column('recommendation_traces', sa.Column('calculations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_traces', 'calculations')
    op.drop_column('recommendation_traces', 'business_rules')
    op.drop_column('recommendation_traces', 'input_metrics')
    op.drop_column('recommendation_traces', 'response_timestamp')
    op.drop_column('recommendation_traces', 'raw_response')
    op.drop_column('recommendation_traces', 'raw_prompt')
    op.drop_column('recommendation_traces', 'system_prompt_hash')
    op.drop_column('recommendation_traces', 'top_k')
    op.drop_column('recommendation_traces', 'top_p')
    op.drop_column('recommendation_traces', 'temperature')
    op.drop_column('recommendation_traces', 'llm_model_version')
    op.drop_column('recommendation_traces', 'llm_model')
    op.drop_column('recommendation_traces', 'llm_provider')
    op.drop_column('recommendation_traces', 'created_from_query')
    op.drop_column('recommendation_traces', 'source_agent')
    op.drop_column('recommendation_traces', 'trigger_type')
    op.drop_column('recommendation_traces', 'triggered_by_email')
    op.drop_column('recommendation_traces', 'triggered_by_user_id')
    op.drop_index(op.f('ix_recommendation_audit_events_trace_id'), table_name='recommendation_audit_events')
    op.drop_index(op.f('ix_recommendation_audit_events_id'), table_name='recommendation_audit_events')
    op.drop_table('recommendation_audit_events')
    # ### end Alembic commands ###
