# ==============================================================================
# PURPOSE: Pydantic schemas for Agent Task definition and input validation.
# DATA FLOW: Generated by the Planner, processed by the Orchestrator, and fed to agents.
# EXTENSION POINTS: Add task priority fields, retry counts, or custom validation rules.
# ARCHITECTURAL DECISION:
# - Strict schema validation ensures that task inputs match agent expectations,
#   preventing runtime errors inside agent loops.
# ==============================================================================

from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class TaskNodeSchema(BaseModel):
    """
    Validation schema for a single task node within a task graph.
    """
    id: str = Field(..., description="Unique task identifier, e.g. 'inventory_run_1'")
    name: str = Field(..., description="Action name of the task, e.g. 'predict_stockout'")
    agent_role: str = Field(..., description="Role of the target agent, e.g. 'inventory'")
    description: str = Field(..., description="Description of the task to execute")
    dependencies: List[str] = Field(default_factory=list, description="IDs of tasks that must run before this one")
    inputs: Dict[str, Any] = Field(default_factory=dict, description="Input arguments required by the agent tool")
    status: str = Field(default="pending", description="Current status: pending, running, completed, failed")
    output: Optional[Dict[str, Any]] = Field(None, description="Output generated by the task execution")
    error: Optional[str] = Field(None, description="Error message if task execution failed")


class TaskGraphSchema(BaseModel):
    """
    Validation schema for a complete task execution graph.
    """
    nodes: Dict[str, TaskNodeSchema] = Field(..., description="Map of node ID to TaskNodeSchema definition")
    organization_id: int = Field(..., description="Target tenant identifier")
