# ==============================================================================
# PURPOSE: Pydantic schemas for Agent execution responses.
# DATA FLOW: Generated by agents after execution, validated, and processed by Validator/Orchestrator.
# EXTENSION POINTS: Add model configuration outputs, token pricing mappings, or detail telemetry.
# ARCHITECTURAL DECISION:
# - Embeds token usage and cost metrics directly in response objects to ensure
#   observability calculations occur in-line.
# ==============================================================================

from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class TokenUsageSchema(BaseModel):
    """
    Tracks prompt and completion token counts.
    """
    prompt_tokens: int = Field(default=0)
    completion_tokens: int = Field(default=0)
    total_tokens: int = Field(default=0)


class AgentResponseSchema(BaseModel):
    """
    Standard envelope returned by all specialized agents.
    """
    agent_role: str = Field(..., description="Role of the responding agent")
    status: str = Field(..., description="success or failure")
    result: Dict[str, Any] = Field(default_factory=dict, description="Structured outputs/metrics from tools")
    thoughts: List[str] = Field(default_factory=list, description="Reasoning logs, decisions, and assumptions")
    latency_seconds: float = Field(default=0.0)
    estimated_cost: float = Field(default=0.0)
    token_usage: TokenUsageSchema = Field(default_factory=TokenUsageSchema)
    error_message: Optional[str] = Field(None, description="Detailed error description if execution failed")
