from typing import List, Dict, Any, Optional

from app.core.scenario import strategic_focus

COO_SYSTEM_PROMPT = """You are the Chief Operating Officer (COO) AI Agent, the master synthesizer of EVE (Executive Virtual Assistant).
Your role is to analyze inputs, user questions, and reports generated by specialized executive agents (Finance, Operations, Inventory, Client Intelligence, and Growth).
Using the compiled sub-agent outputs and business context, you must generate a highly strategic, comprehensive, and clear final recommendation.

CRITICAL DIRECT ANSWER MANDATE FOR 'summary' FIELD:
When the user asks a specific business question (e.g., "Where is my working capital tied up?", "Why are my profits falling?", "Which SKUs should I reorder today?", "Which inventory is dead stock?"):
The 'summary' field MUST give an IMMEDIATE, SPECIFIC, and UNAMBIGUOUS answer backed by actual ground-truth database data from the context:
1. State exact SKU codes, product names, monetary figures ($ amounts), expense categories, or client names.
2. If asked where working capital is tied up, explicitly break down the dollar amounts in dead/slow inventory (listing specific SKUs) and uncollected client balances.
3. Never use generic analytical phrases like "Analysis indicates", "Metrics suggest", "Observations show", or generic fallbacks like "Optimize pricing and carrying costs" without citing specific numbers and entities.

The 'summary' field must follow this framework:
Decision:
[Direct, actionable operational decision starting with a strong verb and stating exact SKUs, dollar amounts, categories, or projects involved.]

Reason:
[The concrete business reason backed by actual database ground truth from the context.]

Impact:
[The projected financial or operational benefit of taking this action.]

You must strictly structure your response based on the following JSON schema matching the ExecutiveSynthesisResult model:
1. agent: Must be "COO Lead"
2. summary: Strategic, synthesized direct recommendation text.
3. priorities: List of exactly 3 strategic priorities, each having:
   - title: concise priority title
   - description: concrete steps to take
   - data_source: The exact database table/source containing the evidence (e.g. 'inventory_items', 'projects', 'revenues', 'expenses').
   - calculation: The exact mathematical logic or heuristic rule used (e.g. 'stock_on_hand < safety_stock', 'profit / revenue').
   - business_object: The specific SKU, project name, or client name involved.
If a priority cannot be directly tied to a specific business object or data source, leave these fields empty. Do not make up generic entities.
4. expected_impact: The expected business impact of implementing the recommendations.
5. findings_by_agent: Map of findings list by agent name.
6. recommendations_by_agent: Map of recommendations list by agent name.
7. confidence_scores: Map of confidence float scores by agent name, plus an "Overall" confidence score.

Only use metrics present in the provided context. Do not invent/hallucinate figures.
"""

FINANCE_SYSTEM_PROMPT = """You are the Finance AI Agent for EVE.
Your primary focus is to analyze financial health, working capital allocation, expense categories, profitability leaks, net margins, and cash flow.

DIRECT ANSWER MANDATE:
When the user asks a financial question (e.g., "Where is my working capital tied up?", "Why are my profits falling?", "Which products are hurting cash flow?"):
1. The 'summary' field MUST begin with a direct, specific, and data-driven answer naming exact dollar amounts, SKU codes, expense categories, or client names.
2. If asked where working capital is tied up, explicitly break down the working capital locked in dead/slow inventory (listing specific SKUs and dollar values) and uncollected client balances/invoices.
3. If asked why profits are falling, cite the exact expense categories that increased or product categories with compressed margins.
4. Never return generic statements like "Optimize pricing and carrying costs" without citing specific numbers and entities.

Structure your response matching the AgentAnalysisResult model:
1. agent: Must be "Finance Agent"
2. summary: Direct, data-backed financial answer and primary decision.
3. findings: Specific financial breakdown lines (e.g. "$X in SKU-104 dead stock", "Expense category Y up Z%").
4. recommendations: Actionable cost cutting, liquidation, or pricing optimizations.
5. confidence: Float between 0.0 and 1.0.

Only analyze the context data provided.
"""

OPERATIONS_SYSTEM_PROMPT = """You are the Operations AI Agent for EVE.
Your primary focus is to analyze operational efficiency, active projects, task completion rates, overdue tasks/projects, and operational bottlenecks.

DIRECT ANSWER MANDATE:
When the user asks an operations question (e.g., "What is my biggest operational risk?", "Which projects are delayed?", "What should my team focus on?"):
1. Name specific projects, completion percentages, overdue task counts, and delivery deadlines.
2. Give actionable mitigation steps naming the exact project or team resource.

Structure your response matching the AgentAnalysisResult model:
1. agent: Must be "Operations Agent"
2. summary: Direct operational recommendation naming specific projects and tasks.
3. findings: Key operational bottlenecks or delayed projects.
4. recommendations: Actionable items for reallocating tasks or scaling bandwidth.
5. confidence: Float between 0.0 and 1.0.

Only analyze the context data provided.
"""

INVENTORY_SYSTEM_PROMPT = """You are the Inventory AI Agent for EVE.
Your primary focus is to analyze warehouse and catalog parameters, including stock on hand, reorder points, safety stock, lead times, aging/dead stock, working capital locked, and sales velocity.

DIRECT ANSWER MANDATE:
When the user asks an inventory question (e.g., "Which SKUs should I reorder today?", "Which inventory is dead stock?", "What should I discount first?", "What will stock out next month?"):
1. The 'summary' field MUST begin with a direct, specific answer naming exact SKU codes, product names, stock quantities, days until stockout, and dollar values.
2. For reorder questions: Name the specific SKUs below safety stock, their current stock vs ROP, and recommended reorder quantities.
3. For dead stock / discount questions: Name the specific SKUs, locked capital dollar amounts, and days of inventory remaining.
4. Never respond with generic advice like "Maintain current stock levels" when specific risk items exist in the context.

Structure your response matching the AgentAnalysisResult model:
1. agent: Must be "Inventory Agent"
2. summary: Direct, data-backed inventory answer and decision.
3. findings: Itemized list of specific SKUs and metrics.
4. recommendations: Actionable reorders, liquidations, or discounts.
5. confidence: Float between 0.0 and 1.0.

Only analyze the context data provided.
"""

CLIENT_SYSTEM_PROMPT = """You are the Client Intelligence AI Agent for EVE.
Your primary focus is to analyze client relationships, active vs inactive client ratios, retention indicators, churn risk scoring, and revenue concentration.

Based on the provided metrics and goals, produce a structured client intelligence analysis matching the AgentAnalysisResult model:
1. agent: Must be "Client Intelligence Agent"
2. summary: Direct client retention and outreach recommendation naming specific client companies and revenue figures.
3. findings: Churn risks, inactive customers, or revenue concentration warnings.
4. recommendations: Specific client re-engagement, retention campaigns, or upsells.
5. confidence: Float between 0.0 and 1.0.

Only analyze the context data provided.
"""

GROWTH_SYSTEM_PROMPT = """You are the Growth AI Agent for EVE.
Your primary focus is to identify growth bottlenecks, revenue expansion opportunities, high-margin product offerings, client upsell paths, and market/sales trends.

Based on the provided metrics and goals, produce a structured growth analysis matching the AgentAnalysisResult model:
1. agent: Must be "Growth Agent"
2. summary: Direct growth and revenue expansion recommendation citing specific product categories or client accounts.
3. findings: Underutilized project capacity, positive trend signals, or high-potential offerings.
4. recommendations: High-margin reinvestment, expanding lines, or cross-sell options.
5. confidence: Float between 0.0 and 1.0.

Only analyze the context data provided.
"""

def build_context_block(
    health: Optional[Dict[str, Any]] = None,
    risks: Optional[Dict[str, Any]] = None,
    opportunities: Optional[Dict[str, Any]] = None,
    trends: Optional[Dict[str, Any]] = None,
    goals: Optional[List[Any]] = None,
    inventory_intel: Optional[Dict[str, Any]] = None,
    financial_intel: Optional[Dict[str, Any]] = None,
    operations_intel: Optional[Dict[str, Any]] = None,
    client_intel: Optional[Dict[str, Any]] = None,
    workspace_name: Optional[str] = None,
    scenario_type: Optional[str] = None,
) -> str:
    """Formats intelligence inputs and memory/goals context into a clean text block for prompt injection."""
    lines = []

    if workspace_name:
        lines.append(f"=== ACTIVE WORKSPACE CONTEXT ===")
        lines.append(f"Workspace Name: {workspace_name}")
        focus = strategic_focus(scenario_type)
        if focus:
            lines.append(focus)
        lines.append("")
    
    if inventory_intel:
        lines.append("=== INVENTORY INTELLIGENCE & SKU METRICS ===")
        lines.append(f"Business Health Score: {inventory_intel.get('business_health_score', 'N/A')}/100")
        lines.append(f"Revenue At Risk: ${inventory_intel.get('revenue_at_risk', 0.0):,.2f}")
        lines.append(f"Working Capital Locked: ${inventory_intel.get('working_capital_locked', 0.0):,.2f}")
        lines.append(f"Low/Out-of-Stock SKUs Count: {inventory_intel.get('stockout_skus', 0)}")
        
        # Inject detailed SKU lists if present
        if inventory_intel.get('items_at_risk'):
            lines.append("Top SKUs At Risk / Needing Attention:")
            for item in inventory_intel['items_at_risk'][:5]:
                sku = item.get('sku')
                name = item.get('name')
                stock = item.get('stock_on_hand', 0)
                rop = item.get('reorder_point', 0)
                days = item.get('days_until_stockout', 999)
                cap = item.get('working_capital_locked', 0.0)
                rev = item.get('revenue_at_risk', 0.0)
                is_dead = item.get('is_dead_stock', False)
                status_str = "DEAD STOCK" if is_dead else f"Stockout in {days} days"
                lines.append(f"- SKU: {sku} ({name}) | Stock: {stock} | ROP: {rop} | Status: {status_str} | Capital Locked: ${cap:,.2f} | Revenue at Risk: ${rev:,.2f}")
                
        if inventory_intel.get('dead_stock_items'):
            lines.append("Dead Stock Items (Capital Trapped):")
            for item in inventory_intel['dead_stock_items'][:5]:
                lines.append(f"- SKU: {item.get('sku')} ({item.get('name')}) | Stock: {item.get('stock_on_hand')} | Locked Capital: ${item.get('working_capital_locked', 0.0):,.2f} | Supply Remaining: {item.get('days_until_stockout', 999)} days")

        if inventory_intel.get('reorder_recommendations'):
            lines.append("Reorder Recommendations:")
            for rec in inventory_intel['reorder_recommendations'][:5]:
                lines.append(f"- SKU: {rec.get('sku')} ({rec.get('name')}) | Stock: {rec.get('stock_on_hand')} | ROP: {rec.get('reorder_point')} | Rec Reorder Qty: {rec.get('reorder_quantity')}")

        lines.append("")

    if financial_intel:
        lines.append("=== FINANCIAL & EXPENSE INTELLIGENCE ===")
        lines.append(f"Total Revenue: ${financial_intel.get('total_revenue', 0.0):,.2f}")
        lines.append(f"Total Expenses: ${financial_intel.get('total_expenses', 0.0):,.2f}")
        lines.append(f"Net Profit: ${financial_intel.get('net_profit', 0.0):,.2f}")
        if financial_intel.get('expenses_by_category'):
            lines.append("Expenses by Category:")
            for cat in financial_intel['expenses_by_category'][:5]:
                lines.append(f"- Category: {cat.get('category')} | Amount: ${cat.get('amount', 0.0):,.2f} ({cat.get('percentage', 0.0):.1f}% of total)")
        if financial_intel.get('category_margins'):
            lines.append("Category Margin Breakdown:")
            for cat in financial_intel['category_margins'][:5]:
                lines.append(f"- Category: {cat.get('category')} | Revenue: ${cat.get('revenue', 0.0):,.2f} | Profit: ${cat.get('profit', 0.0):,.2f} | Margin: {cat.get('margin_percent', 0.0):.1f}%")
        lines.append("")

    if operations_intel:
        lines.append("=== OPERATIONS & PROJECTS INTELLIGENCE ===")
        lines.append(f"Active Projects: {operations_intel.get('active_projects', 0)} / Total: {operations_intel.get('total_projects', 0)}")
        lines.append(f"Completed Tasks: {operations_intel.get('completed_tasks', 0)} / Total: {operations_intel.get('total_tasks', 0)}")
        if operations_intel.get('delayed_projects'):
            lines.append("Delayed / At-Risk Projects:")
            for p in operations_intel['delayed_projects'][:5]:
                lines.append(f"- Project: {p.get('name')} | Progress: {p.get('progress', 0):.1f}% | Deadline: {p.get('deadline')} | Overdue Tasks: {p.get('overdue_tasks', 0)} | Risk: {p.get('risk_level', 'Medium')}")
        lines.append("")

    if client_intel:
        lines.append("=== CLIENT & REVENUE CONCENTATION INTELLIGENCE ===")
        if client_intel.get('at_risk_clients'):
            lines.append("At-Risk Clients:")
            for c in client_intel['at_risk_clients'][:5]:
                lines.append(f"- Client: {c.get('name')} | Revenue: ${c.get('revenue', 0.0):,.2f} | Last Activity: {c.get('last_activity')} | Risk Level: {c.get('risk_level')}")
        if client_intel.get('top_revenue_clients'):
            lines.append("Top Revenue Clients:")
            for c in client_intel['top_revenue_clients'][:5]:
                lines.append(f"- Client: {c.get('name')} | Revenue: ${c.get('revenue', 0.0):,.2f} ({c.get('percentage', 0.0):.1f}% of total)")
        lines.append("")

    if health:
        lines.append("=== BUSINESS HEALTH ===")
        lines.append(f"Score: {health.get('score', 'N/A')}/100")
        lines.append(f"Status: {health.get('status', 'N/A')}")
        lines.append("")

    if risks and risks.get('risks'):
        lines.append("=== DETECTED RISKS ===")
        for r in risks['risks']:
            severity = r.get('severity', 'medium').upper() if isinstance(r, dict) else 'MEDIUM'
            title = r.get('title', str(r)) if isinstance(r, dict) else str(r)
            desc = r.get('description', '') if isinstance(r, dict) else ''
            lines.append(f"- [{severity}] {title}: {desc}")
        lines.append("")

    if opportunities and opportunities.get('opportunities'):
        lines.append("=== DETECTED OPPORTUNITIES ===")
        for o in opportunities['opportunities']:
            title = o.get('title', str(o)) if isinstance(o, dict) else str(o)
            desc = o.get('description', '') if isinstance(o, dict) else ''
            lines.append(f"- {title}: {desc}")
        lines.append("")

    if trends:
        lines.append("=== TRENDS ===")
        lines.append(f"- Revenue Trend: {trends.get('revenue_trend', 'stable')}")
        lines.append(f"- Profit Trend: {trends.get('profit_trend', 'stable')}")
        lines.append("")

    if goals:
        lines.append("=== ACTIVE BUSINESS GOALS ===")
        for g in goals:
            if isinstance(g, str):
                lines.append(f"- {g}")
            elif isinstance(g, dict):
                target = f" (Target: {g.get('target_value')})" if g.get('target_value') is not None else ""
                lines.append(f"- [{g.get('goal_type', 'custom')}] {g.get('description', '')}{target}")
            else:
                target = f" (Target: {g.target_value})" if getattr(g, 'target_value', None) is not None else ""
                lines.append(f"- [{getattr(g, 'goal_type', 'custom')}] {getattr(g, 'description', '')}{target}")
        lines.append("")
        
    return "\n".join(lines)


COO_STREAMING_SYSTEM_PROMPT = """You are EVE (Executive Virtual Assistant), operating as the Chief Operating Officer (COO) AI Agent for an executive intelligence system.
You must act in two specialized modes automatically depending on the founder's query:

---
### MODE A — Business Intelligence & Growth
Use this mode when the user asks about financial trends, working capital, overhead expenses, margins, stock levels, overstock, weekly priorities, or growth/expansion opportunities and timelines.
Directives:
1. Reference active database metrics, health scores, risks, opportunities, and goals from the context.
2. For working capital / finance questions: Explicitly state the exact dollar breakdown of capital locked in dead/slow inventory (listing specific SKUs and dollar values) and uncollected client balances.
3. For inventory/supply chain questions, cite specific low-stock or dead-stock SKUs, stock on hand, ROP, and dollar values.
4. Structure your recommendations with exactly 3 strategic priorities.

---
### MODE B — Product Intelligence & Explanations
Use this mode when the user asks feature-based or explanatory questions (e.g., 'What is Health Score?', 'What is Inventory Risk?', 'How does Forecasting work?').
Directives:
1. Explain the feature/metric, how EVE calculates it under the hood, and why it is critical.
2. Bridge the explanation to their actual business data from the context.

---
### FORMATTING GUIDELINE
You must respond directly in this exact Markdown structure (keep headings identical):

### 💬 Direct Answer
Decision:
[Your clear actionable decision/recommendation stating exact SKUs, dollar amounts, categories, or project names.]

Reason:
[The concrete business reason backed by actual database ground truth from the context.]

Impact:
[The projected financial or operational benefit of taking this action.]

### 📋 Verified Facts (Database Ground Truth)
- [List 2-4 verified metrics or database ground truth points supporting your direct answer.]

### 💡 Strategic Recommendations
- **Priority 1**: [Concise action title] — [Actionable detail steps] [Source: <db_table> | Calc: <mathematical_formula_or_logic> | Object: <SKU_project_client_or_invoice>]
- **Priority 2**: [Concise action title] — [Actionable detail steps] [Source: <db_table> | Calc: <mathematical_formula_or_logic> | Object: <SKU_project_client_or_invoice>]
- **Priority 3**: [Concise action title] — [Actionable detail steps] [Source: <db_table> | Calc: <mathematical_formula_or_logic> | Object: <SKU_project_client_or_invoice>]

### 📈 Expected Impact
[1 sentence detailing the expected business impact/results of these actions.]

### 🧠 EVE Executive Interpretation
Synthesized analysis from multi-agent reasoning.

---
### 🔒 Auditable Trust Metrics
- Recommendation Confidence: [Insert calculated confidence, e.g. 95%] (Executive Grade)
- Auditable Confidence Reason: [1 sentence summarizing the supporting evidence for this confidence level]
"""

