# ==============================================================================
# PURPOSE: Schema specification for the CEO Executive Summary Report artifact.
# DATA FLOW: Compiled by the CEO Agent, serialized to JSON, and saved in the DB.
# EXTENSION POINTS: Add brand action item check grids or custom strategic recommendations.
# ==============================================================================

from typing import Dict, Any
from pydantic import BaseModel, Field


class ExecutiveReportTemplate(BaseModel):
    """
    Consolidated executive report compiled by the CEO Agent.
    """
    inventory_risk_score: float = Field(..., description="Average stockout risk score of the brand")
    total_reorder_recommendations: int = Field(..., description="Total purchase orders suggested")
    total_dead_stock_items: int = Field(..., description="Total dead stock items needing markdowns")
    total_pricing_adjustments: int = Field(..., description="Total dynamic pricing changes suggested")
    estimated_profit_impact: float = Field(..., description="Net projected profit improvement dollars")
    strategic_recommendation: str = Field(..., description="Textual strategic advice generated by CEO agent")
    agent_telemetry: Dict[str, Any] = Field(default_factory=dict, description="Execution node details and trace paths")
class Config:
    from_attributes = True

def generate_executive_summary(
    stockout_count: int,
    dead_stock_count: int,
    total_reorders: int,
    total_profit_impact: float
) -> str:
    """
    Generates a deterministic executive summary based on the calculated metrics.
    """
    return (
        f"{stockout_count} products are at risk of stockout.\n"
        f"{dead_stock_count} products are dead stock.\n"
        f"Recommended reorders total {total_reorders} units.\n"
        f"Potential profit improvement is ${total_profit_impact:,.0f}."
    )
