# ==============================================================================
# PURPOSE: Schema specification for the Inventory Report artifact.
# DATA FLOW: Generated by the Inventory Agent, serialized to JSON, and saved in the DB.
# EXTENSION POINTS: Add replenishment safety indexes or vendor supply statuses.
# ==============================================================================

from typing import List, Dict, Any
from pydantic import BaseModel, Field


class InventoryReportTemplate(BaseModel):
    """
    Structural specification for compiled inventory analytics reports.
    """
    total_skus: int = Field(..., description="Total unique SKUs tracked in the warehouse")
    out_of_stock_skus: int = Field(..., description="Count of SKUs currently out of stock")
    low_stock_skus: int = Field(..., description="Count of SKUs below safety stock limits")
    dead_stock_skus: int = Field(..., description="Count of SKUs identified as slow-moving/dead stock")
    average_risk_score: float = Field(..., description="Average stockout risk index (0 to 100)")
    estimated_reorder_cost: float = Field(..., description="Total cost of recommended purchase orders")
    items_at_risk: List[Dict[str, Any]] = Field(default_factory=list, description="Detailed analysis per SKU")
    dead_stock_items: List[Dict[str, Any]] = Field(default_factory=list, description="List of dead stock SKUs requiring markdowns")
