# ==============================================================================
# PURPOSE: Schema specification for the Dynamic Pricing Report artifact.
# DATA FLOW: Generated by the Pricing Agent, serialized to JSON, and saved in the DB.
# EXTENSION POINTS: Add competitive price comparison indices or discount matrices.
# ==============================================================================

from typing import List, Dict, Any
from pydantic import BaseModel, Field


class PricingReportTemplate(BaseModel):
    """
    Structural specification for compiled dynamic pricing suggestions.
    """
    average_current_margin: float = Field(..., description="Average catalog margin today")
    average_recommended_margin: float = Field(..., description="Average catalog margin if recommended adjustments are made")
    estimated_revenue_impact: float = Field(..., description="Net gross revenue delta across recommended items")
    estimated_profit_impact: float = Field(..., description="Net gross profit delta across recommended items")
    recommendations: List[Dict[str, Any]] = Field(default_factory=list, description="SKU recommendations details list")
