# ==============================================================================
# PURPOSE: Schema specification for the Supplier Sourcing Report artifact.
# DATA FLOW: Generated by the Sourcing Agent, serialized to JSON, and saved in the DB.
# EXTENSION POINTS: Add landed duty calculations or manufacturer audit scores.
# ==============================================================================

from typing import List, Dict, Any
from pydantic import BaseModel, Field


class SourcingReportTemplate(BaseModel):
    """
    Structural specification for supplier comparisons.
    """
    suppliers: List[Dict[str, Any]] = Field(default_factory=list, description="Vendor quotes comparison grids")
    lowest_cost_option: Dict[str, Any] = Field(..., description="Details on the cheapest vendor option")
    lowest_risk_option: Dict[str, Any] = Field(..., description="Details on the most reliable/fastest vendor option")
